### ISSUE TITLE
Problem with Clarity

### ISSUE THREAD

**Issue by alexej-strelzow** [MrFrankel/share-loader#12]
Hi Mr Frankel,

I'm trying to use [(clarity)](https://clarity.design/documentation/get-started) as a component library and it's not going very well.
I've tried many approaches with the webpack and cli-way for the shell app. I've tried to share the library via the shell-app. Both times, AppModule cannot get loaded properly. 
> ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'AppModule' of undefined

The standalone approach does not work either. Strangely, for the cli-approach, even though "vendorChunk": false is configured in angular.json, it gets generated. So I end up with main.js and vendor.js. Unfortunately I am not able to bundle everything in just one bundle.

When I exclude the components that use clarity from the external app - the shell app works. Maybe this is related to the @angular/material issue. 

Maybe, if you have time, you can give it a try. Are you using component libraries in your projects that you share via the composition layer?

Many thanks!
Alexej

**Comment by alexej-strelzow** [comment]
I could get it to work with both techniques. I am not sharing any clarity modules now and I had to load the vendor.js from the external app prior loading the external app.

**Comment by MrFrankel** [comment]
can you provide a repo?

**Comment by alexej-strelzow** [comment]
Sorry for the late reply, I'll provide one by the end of the week!

**Comment by alexej-strelzow** [comment]
issue resolved, needed to provide those two module entries /@clr\/angular/,/@clr\/ui/
