### ISSUE TITLE
How can I use existing angular 7 application as external app. Please provide steps to follow.

### ISSUE THREAD

**Issue by amaneer94** [MrFrankel/share-loader#13]

**Comment by MrFrankel** [comment]
@amaneer94 the example application in the repo are Angular 7, both webpack and CLI. you can follow them, if you have specific questions let me know.

**Comment by alexej-strelzow** [comment]
@amaneer94 , as MrFrankel pointed out, but here are the key steps:
1. add build-ext script to angular.json (references extra-webpack.config.js)
2. add extra-webpack.config.js (contains config for share-loader)
3. add app.external.module (does not bootstrap any AppComponent)
4. make sure everyting is bundled in one bundle (--no-vendor-chunk) or --configuration production (uses production properties in build-ext in angular.json), but aot=false, buildOptimizer=false
5. you might have to export your apps css styles and load dem in index.html in your composition layer (--extract-css)

**Comment by amaneer94** [comment]
@alexej-strelzow much appreciated. I will try those steps. Closing the issue. Just in case of further queries on it will re-open the issue.

**Comment by alexej-strelzow** [comment]
@amaneer94 : you're welcome. What helped me was to create an angular project from scratch (ng new ...) and then try to get it work with share-loader (as shown in the example-cli folder). I think that helps you the most in understanding everything - details matter (e.g. library name in extra-webpack config and bootstrapping in sLoader.ts in composition layer, etc.).
