### ISSUE TITLE
How to use ngx-translate/core with child application

### ISSUE THREAD

**Issue by marcelo-vrgs** [MrFrankel/share-loader#16]
Hi guys! 

I'm using ngx-translate/core (https://github.com/ngx-translate/core), but I can't find a way to execute the step "2. Init the TranslateService for your application".

The problem is how to execute the code below in a child application. The common way is to use the appComponent constructor and the code will run just with the first load, but with share-loader I can't find a place to do this.

`@Component({
    selector: 'app',
    template: `
        <div>{{ 'HELLO' | translate:param }}</div>
    `
})
export class AppComponent {
    param = {value: 'world'};

    constructor(translate: TranslateService) {
        // this language will be used as a fallback when a translation isn't found in the current language
        translate.setDefaultLang('en');

         // the lang to use, if the lang isn't available, it will use the current loader to get them
        translate.use('en');
    }
}`

I've tried to use APP_INITIALIZER, but the function was not fired with ext project.

`
....
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: onAppInit1,
      multi: true,
      deps: [/* your dependencies */]
    }
  ],
....
export class AppCommonModule {}

export function onAppInit1(/* dependencies */): () => Promise<any> {
  return (): Promise<any> => {
    return new Promise((resolve, reject) => {
      console.log(`onAppInit1:: inside promise`);
    });
  };
}`

Do you have any suggestion?

**Comment by MrFrankel** [comment]
can you provide a repro ?

**Comment by marcelo-vrgs** [comment]
I put the code at:
https://github.com/marcelo-vrgs/share-loader-with-ngxtranslate

The main problem is  that I've routes to many external components and I need to initialize ngx-translate every time just because I don't have a common entry point (eg.: ).
Example:
1 - Click at "external app 2 (without translation initializer)" -> the message is "Show common.greetings"
2- Click at "external app (with translation initializer)" -> Here we can see translated messages
3 - Click again at "external app 2 (without translation initializer)" -> now the message is translated to Show Olá""

I have tried with APP_INITIALIZER, but it's called just from shell-app (you can see console messages)

**Comment by MrFrankel** [comment]
@marcelo-vrgs  the issue you are facing is caused due to you not sharing the translate module between you apps. each one is running it's own instance and therefore needs reinitialized.

Iv'e created a PR in your reporo, let me know if it's clear.

https://github.com/marcelo-vrgs/share-loader-with-ngxtranslate/pull/1

**Comment by MrFrankel** [comment]
@marcelo-vrgs can we close this?

**Comment by marcelo-vrgs** [comment]
Yes, it's all clear now
