### ISSUE TITLE
Problem with Angular 7 Library

### ISSUE THREAD

**Issue by sanjaypraja** [MrFrankel/share-loader#17]
Hi @MrFrankel 

I have create Library in Angular 7 which have one service with one function. 
Create Library with these steps 
1. command ng generate library {libraryname}. 
2. create one service "UtilService" with one function
3. ng build {libraryname}
4. install new library in ext-app.
5. & also install in shell app. 

My project is working fine without new library (both ext and shell app).  Also I have used external Library like "angular2-notifications" is working fine but problem is coming only with our new library. 

Error is 
![image](https://user-images.githubusercontent.com/2256488/60041748-c3e2c880-96d9-11e9-87c3-9dd1be07b39d.png)

Can you please help me how we can add our own library?

**Comment by MrFrankel** [comment]
Can you provide a reporo?

**Comment by sanjaypraja** [comment]
Libray code is here: https://drive.google.com/file/d/1-8z8Ws3k0bH4kXF-stWrFZqtVOgJF38z/view?usp=sharing

**Comment by sanjaypraja** [comment]
Hi @MrFrankel 
Hope you find code.  I have tried with current version share-loader but error found. 
![image](https://user-images.githubusercontent.com/2256488/60093765-e7545480-9767-11e9-8814-d2ee50aeaf66.png)

**Comment by MrFrankel** [comment]
@sanjaypraja I will look at it later today I hope

**Comment by sanjaypraja** [comment]
@MrFrankel have you any chance to look these issues? For Angular CLI ext-app1 &

**Comment by MrFrankel** [comment]
Unfortunately I have not had the time, I hope to get to it in the next couple of days.

**Comment by sanjaypraja** [comment]
@MrFrankel Anngular CLI project is working fine. it was some version problem in my system.

**Comment by sanjaypraja** [comment]
@MrFrankel I think I got solution, It was my mistake not give reference in Shell-app extra-webpack.config.js.
