### ISSUE TITLE
How to provide two different Angular Versions in Shell App

### ISSUE THREAD

**Issue by alexej-strelzow** [MrFrankel/share-loader#18]
Scenario: Shell App and some MF are in Angular 7, and now an Angular 8 app should get integrated into the Shell/Composition Layer (CL). 

What I have so far:
Both dependencies in CL - Angular 8 installed as Alias as follows:
```
"dependencies": {
 "@angular8/animations": "npm:@angular/animations@^8.1.2",
 "@angular8/common": "npm:@angular/common@^8.1.2",
 "@angular8/compiler": "npm:@angular/compiler@^8.1.2",
 "@angular8/core": "npm:@angular/core@^8.1.2",
 "@angular8/forms": "npm:@angular/forms@^8.1.2",
 "@angular8/platform-browser": "npm:@angular/platform-browser@^8.1.2",
 "@angular8/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@^8.1.2",
 "@angular8/router": "npm:@angular/router@^8.1.2",

 "@angular/animations": "~7.2.0",
 "@angular/common": "~7.2.0",
 "@angular/compiler": "~7.2.0",
 "@angular/core": "~7.2.0",
 "@angular/forms": "~7.2.0",
 "@angular/platform-browser": "~7.2.0",
 "@angular/platform-browser-dynamic": "~7.2.0",
 "@angular/router": "~7.2.0",
  ...
}
```

Result:
![image](https://user-images.githubusercontent.com/16270237/61465176-d4ecc580-a977-11e9-9c41-8f34f6da0f88.png)

I am able to provide Angular 8 in the window object with the following configuration:
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.js?$/,
        use:
          [{
            loader: 'share-loader',
            options: {
              modules: [/@angular/, /@clr\/angular/, /@clr\/ui/, /rxjs/, /@ngxs\/store/, /@ngxs-labs\/emitter/],
              exclude: [/@angular-devkit/, /angular8/],
              namespace: 'lucy-web-app'
            }
          },
            {
              loader: 'share-loader',
              options: {
                modules: [/angular8/],
                exclude: [],
                namespace: 'angular-8'
              }
            }]
      }]
  }
};
```
It is really there:
![image](https://user-images.githubusercontent.com/16270237/61465276-0b2a4500-a978-11e9-9201-8798c22f84dd.png)

**Question:**
What is the best way to point the MF written in Angular 8 to this namespace?
Can I just do it with share-loader or do I have to write a custom Webpack-Loader?

The problem is, that Angular 8 is in the CL inside node_modules/@angular8  -  but the MF imports it in the source from @angular. So I must somehow link them together, but how?

**Comment by MrFrankel** [comment]
@alexej-strelzow since this solution relies on providing a module that will be imported at run time to the app module both application need to share a single Anguar instance.
If you want to run your external application with a different Angular instance I suggest you compile it without the externals webpack configuration and bootstrap it’s app module to a separate node in the DOM.

However I must say I highly recommend not working with two versions of Angular on the same page, this will have an impact on performance.

**Comment by MrFrankel** [comment]
If you do want to access the angular8 instance from the external application you can do it via the externals configuration in the external package webpack config. i.e:
externals:
{
angular: ‘angular-8’
}

**Comment by alexej-strelzow** [comment]
@MrFrankel : you're right
This is not a good idea indeed. I ended up integrating the MF (with Angular != Angular CL) via a wrapper component (in the CL) which embeds the MF via iFrame. So the MF can ship whatever it wants (also Clarity v1 cannot co-exist with Clarity v2 - which is used with Angular 8).

case closed
