### ISSUE TITLE
Not supporting with Angular 7

### ISSUE THREAD

**Issue by sanjaypraja** [MrFrankel/share-loader#2]
Dear Frankel,

Great Solutions ! Thank you.
Given Sample present using UIRouterModule, It's working fine. I tried with Angular 7 using RouterModule but given error. Please suggest me how can i fix it.
ERROR Error: Uncaught (in promise): Error: "extapp" was not created by "http://localhost/ext1.js"
Error: "extapp" was not created by "http://localhost/ext1.js"
    at app.js:90865
    at ZoneDelegate.invoke (vendor.js:119431)
    at Object.onInvoke (app.js:55750)
    at ZoneDelegate.invoke (vendor.js:119430)
    at Zone.run (vendor.js:119181)
    at vendor.js:119915
    at ZoneDelegate.invokeTask (vendor.js:119464)
    at Object.onInvokeTask (app.js:55741)
    at ZoneDelegate.invokeTask (vendor.js:119463)
    at Zone.runTask (vendor.js:119231)
    at app.js:90865
    at ZoneDelegate.invoke (vendor.js:119431)
    at Object.onInvoke (app.js:55750)
    at ZoneDelegate.invoke (vendor.js:119430)
    at Zone.run (vendor.js:119181)
    at vendor.js:119915
    at ZoneDelegate.invokeTask (vendor.js:119464)
    at Object.onInvokeTask (app.js:55741)
    at ZoneDelegate.invokeTask (vendor.js:119463)
    at Zone.runTask (vendor.js:119231)
    at resolvePromise (vendor.js:119857)
    at resolvePromise (vendor.js:119814)
    at vendor.js:119916
    at ZoneDelegate.invokeTask (vendor.js:119464)
    at Object.onInvokeTask (app.js:55741)
    at ZoneDelegate.invokeTask (vendor.js:119463)
    at Zone.runTask (vendor.js:119231)
    at drainMicroTaskQueue (vendor.js:119638)
    at ZoneTask.invokeTask [as invoke] (vendor.js:119543)
    at invokeTask (vendor.js:120583)

**Comment by MrFrankel** [comment]
@sanjaypraja Hey,
Can you please provide the app.module files for both the apps?

**Comment by sanjaypraja** [comment]
**For ext-app-1**

**_ext.prod.module.ts_**

import {NgModule, ApplicationModule, CUSTOM_ELEMENTS_SCHEMA} from '@angular/core';
import {UIRouterModule} from '@uirouter/angular';
import {CommonModule} from '@angular/common';
import {ExtComponent} from './ext.component';
import {WelcomeComponent} from './welcome.component';
import { extRouting } from './app-routing.module';


@NgModule({
  imports: [CommonModule, extRouting],
  declarations: [ExtComponent, WelcomeComponent],
  bootstrap: [],
  entryComponents: [],
  exports: [CommonModule, ApplicationModule],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
  ],
})
export class ExtModule {
}

window['ExtModule'] = ExtModule;

**_app-routing.module.ts_**

import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { WelcomeComponent } from './welcome.component';
import { ExtComponent } from './ext.component';

const routes: Routes = [
  {
    path: 'ext', component: ExtComponent, pathMatch: 'full'
  },
  {
    path: 'welcome', component: WelcomeComponent
  }
];

export const extRouting = RouterModule.forChild(routes);

**For shell-app**

**_app-routing.module.ts_**

import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { App1Component } from './app1.component';
import {loadScript} from './sLoader';

const routes: Routes = [
  {
    path: 'app1', component: App1Component
  },
  {
    path: 'ext',
    loadChildren: () => {
        return loadScript('http://localhost/ext1.js', 'extapp', 'AppModule');
      }
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }

**_app.module.ts_**

import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {AppComponent} from './app.component';
import {SelectComponent} from './select.component';
import {UIRouterModule} from '@uirouter/angular';
import {APP_STATES} from './app.states';
import {App1Component} from './app1.component';
import { AppRoutingModule } from './app-routing.module';

@NgModule({
  imports: [BrowserModule, AppRoutingModule],
  declarations: [AppComponent, SelectComponent, App1Component],
  bootstrap: [AppComponent]
})
export class AppModule {
}

**Comment by MrFrankel** [comment]
this isn't related to Angular 7, it seems you are not configuring the router correctly, ill try to get a sample for you

**Comment by sanjaypraja** [comment]
Thank you for prompt response. I will wait for sample.

**Comment by MrFrankel** [comment]
Iv'e just pushed in an example with Angular router updated to Angular 7

**Comment by sanjaypraja** [comment]
Dear Frankel,

Thank you for share this solution. It is working fine :).

We are going to develop multi product with common components modules & libraries. also use OIDC for authentication and authorization. 

I have few question with your solution to fit in our requirement.

1. I tried to compare between my Angular 7 project with your project then after found that You have not use default angular 7 files like polyfills.ts, angular.json, environments files. have you any specific reason?
2. We have common components and use into multiple modules. How we can use with your solution for this?
3. How can we use angular libraries with your solution?
4. other & last: What is best approach to maintain session into sub projects with OIDC? (this question may be outside box).

**Comment by StephenRansom** [comment]
Hi Sanjay, it appears the answer to your first question might be that you are using angular-cli while MrFrankel does not appear to be. That said, @MrFrankel with angular cli ownership of webpack configs, would you say that this loader is compatible with angular-cli as well as vanilla angular projects?

**Comment by MrFrankel** [comment]
Hey @StephenRansom and @sanjaypraja, Indeed the differences are due to this example project not being an Angular CLI project.
It is however possible to add share-loader to Angular-CLI configuration using custom builders.

I dont have an example of this yet but ill try and get one some time soon, though there are exmples out there for custom builders if you care to try it your self, if you do, please share it here too.

**Comment by MrFrankel** [comment]
as for the other questions.
2. If you have common components between project's you can either exports them to a npm package which you can share between projects, and then at runtime share them from the shell-app via share loader to avoid having multiple instances of them.
3. Same here, you can share the libraries instances using share-loader to avoid having multiple instances at runtime.
4.Not sure what you mean, once an external app is loaded into the shell app, they share the same context, ie, local storage, session storage etc... make sure all apps properly name space and of the resources of this type.

**Comment by MrFrankel** [comment]
I have added an example of using share-loader with Angular-cli, you can look at the example-cli part in the Readme.

**Comment by rohit-neeshu** [comment]
> Dear Frankel,
> 
> Great Solutions ! Thank you.
> Given Sample present using UIRouterModule, It's working fine. I tried with Angular 7 using RouterModule but given error. Please suggest me how can i fix it.
> ERROR Error: Uncaught (in promise): Error: "extapp" was not created by "http://localhost/ext1.js"
> Error: "extapp" was not created by "http://localhost/ext1.js"
> at app.js:90865
> at ZoneDelegate.invoke (vendor.js:119431)
> at Object.onInvoke (app.js:55750)
> at ZoneDelegate.invoke (vendor.js:119430)
> at Zone.run (vendor.js:119181)
> at vendor.js:119915
> at ZoneDelegate.invokeTask (vendor.js:119464)
> at Object.onInvokeTask (app.js:55741)
> at ZoneDelegate.invokeTask (vendor.js:119463)
> at Zone.runTask (vendor.js:119231)
> at app.js:90865
> at ZoneDelegate.invoke (vendor.js:119431)
> at Object.onInvoke (app.js:55750)
> at ZoneDelegate.invoke (vendor.js:119430)
> at Zone.run (vendor.js:119181)
> at vendor.js:119915
> at ZoneDelegate.invokeTask (vendor.js:119464)
> at Object.onInvokeTask (app.js:55741)
> at ZoneDelegate.invokeTask (vendor.js:119463)
> at Zone.runTask (vendor.js:119231)
> at resolvePromise (vendor.js:119857)
> at resolvePromise (vendor.js:119814)
> at vendor.js:119916
> at ZoneDelegate.invokeTask (vendor.js:119464)
> at Object.onInvokeTask (app.js:55741)
> at ZoneDelegate.invokeTask (vendor.js:119463)
> at Zone.runTask (vendor.js:119231)
> at drainMicroTaskQueue (vendor.js:119638)
> at ZoneTask.invokeTask [as invoke] (vendor.js:119543)
> at invokeTask (vendor.js:120583)

@sanjaypraja I am also getting the same error. Did you manage to solve it? I have mark aot:false in both the project angular.json
