### ISSUE TITLE
Load assets

### ISSUE THREAD

**Issue by gesanchez** [MrFrankel/share-loader#20]
Hi!,

I am trying to load an image from the project (not in shell) but the image dont load because is trying to reach it in the shell app

How i can fix this?

thks

**Comment by hboylan** [comment]
My understanding is that this loader is intended for sharing npm packages. Your best bet might be to host the image and reference it via url.

**Comment by MrFrankel** [comment]
@gesanchez, sorry fot the late rely, you can either load the image in base64 form or store it in a globally available url.
