### ISSUE TITLE
Bundle symlinked dependencies

### ISSUE THREAD

**Issue by hboylan** [MrFrankel/share-loader#22]
This loader works great! We're using it to build a [micro-frontend](https://martinfowler.com/articles/micro-frontends.html) application.

One problem I just ran into... We have one NPM package that is being shared between the "container app" and "module" that we would like to `npm link` for development purposes. I'm wondering if it's possible to support with `share-loader`. If so, I'd be happy to contribute!

**Comment by hboylan** [comment]
Actually, I've just found the culprit. Adding the "dot" between `this.query.namespace` and `request` fixed the issue, which you've done [here](https://github.com/MrFrankel/share-loader/blob/master/index.js#L69). So this should be fixed with a simple `npm publish`. 😄

**Comment by MrFrankel** [comment]
@hboylan sorry for the late reply, i've been away. you mean the latest code isn't published?

**Comment by hboylan** [comment]
No worries. I appreciate the reply.

Correct. I've been manually editing `/node_modules/share-loader/index.js` for the time being. Would really appreciate a fresh publish.

**Comment by MrFrankel** [comment]
@hboylan released in 0.7.0
