### ISSUE TITLE
Problems with Angular i18n

### ISSUE THREAD

**Issue by thanikc** [MrFrankel/share-loader#3]
I'm not sure if this issue should be addressed here, but since in the examples you use it with angular. The share-loader breaks the angular application, if i18n is used. When the function `registerLocaleData(data, localeId, extraData)` is called `localeId` is undefined.

**Comment by MrFrankel** [comment]
@thanikc can you provide more details?
Your webpack config? angular.json?

**Comment by thanikc** [comment]
> @thanikc can you provide more details?
> Your webpack config? angular.json?

@MrFrankel I have an example in my [git repository](https://github.com/thanikc/ng-micro/tree/i18n)
The app works until I add these lines to angular.json:
`"i18nFile": "src/i18n/messages.en.xlf",`
`"i18nFormat": "xlf",`
`"i18nLocale": "en",`
The error is then thrown at runtime.

**Comment by MrFrankel** [comment]
ill take a look

**Comment by MrFrankel** [comment]
I dont see in you repo that you are using the share-loader correctly,
I have added a folder in this repo called example-cli, check it out.
It uses @angular-builders/custom-webpack not ngx-build-plus but the concept is the same.

Also, you should probably load the external angular modules using angular Router API(loadchilden)
