### ISSUE TITLE
Problem with @angular/material 

### ISSUE THREAD

**Issue by amaneer94** [MrFrankel/share-loader#4]
I Updated the package.json file which look like following

> {
    "name": "ext-app-1",
    "version": "0.0.0",
    "private": true,
    "dependencies": {
        "@angular/animations": "7.0.4",
        "@angular/cdk": "7.0.4",
        "@angular/common": "7.0.4",
        "@angular/compiler": "7.0.4",
        "@angular/core": "7.0.4",
        "@angular/forms": "7.0.4",
        "@angular/http": "7.0.4",
        "@angular/material": "7.0.4",
        "@angular/material-moment-adapter": "7.0.4",
        "@angular/platform-browser": "7.0.4",
        "@angular/platform-browser-dynamic": "7.0.4",
        "@angular/router": "7.0.4",
        "angular-in-memory-web-api": "0.5.4",
        "angular2-jwt": "^0.2.3",
        "bootstrap": "4.1.3",
        "core-js": "2.5.7",
        "hammerjs": "2.0.8",
        "jquery": "3.3.1",
        "loadash": "^1.0.0",
        "moment": "2.22.2",
        "ng2-cookies": "^1.0.12",
        "ngx-bootstrap": "3.1.1",
        "ngx-image-cropper": "^1.3.8",
        "ngx-toastr": "^9.1.1",
        "popper.js": "1.14.5",
        "rxjs": "6.3.3",
        "rxjs-compat": "^6.4.0",
        "web-animations-js": "2.3.1",
        "zone.js": "0.8.26"
    },
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "devDependencies": {
        "@angular-builders/custom-webpack": "^7.4.1",
        "@angular-devkit/build-angular": "~0.10.0",
        "@angular/cli": "~7.0.2",
        "@angular/compiler-cli": "~7.0.0",
        "@angular/language-service": "~7.0.0",
        "@types/jasmine": "~2.8.8",
        "@types/jasminewd2": "~2.0.3",
        "@types/lodash": "^4.14.121",
        "@types/node": "~8.9.4",
        "codelyzer": "~4.5.0",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~3.0.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.1",
        "karma-jasmine": "~1.1.2",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.4.0",
        "share-loader": "^0.4.0",
        "ts-node": "~7.0.0",
        "tslint": "~5.11.0",
        "typescript": "~3.1.1"
    }
}

and added material module in `app.common.module.ts` which looks like

>   import { DemoMaterialModule } from './material-module';
custom.component';
  import {NgModule} from '@angular/core'
  import {AppComponent} from './app.component'
  import {ExtComponent} from './ext.component'
  import {WelcomeComponent} from './welcome.component'
  export const appModuleRoot: NgModule = {
    imports: [
      DemoMaterialModule
    ],
    declarations: [AppComponent, ExtComponent, WelcomeComponent],
    bootstrap: [],
    providers: [],
    exports: []
  };

My build was successful using this command `npm run ng run ext-app1:build-ext`
But when I open web page in browser and click on load `external app` application crashed with following error 

> material-module.ts:44 Uncaught TypeError: Cannot read property 'MatAutocompleteModule' of undefined
    at material-module.ts:44

Images are attached for reference 
![screenshot from 2019-03-07 16-15-56](https://user-images.githubusercontent.com/16270049/53953121-60199d00-40f4-11e9-8db1-3427d1e2e0a7.png)
![screenshot from 2019-03-07 16-17-00](https://user-images.githubusercontent.com/16270049/53953154-7889b780-40f4-11e9-9a3e-5acb1d8d80a9.png)

**Comment by MrFrankel** [comment]
@amaneer94 did you add material module to the shell-app?

**Comment by amaneer94** [comment]
No, just added in external app

**Comment by MrFrankel** [comment]
So your external app is probably sharing all angular modules from the shell-app, it would probably be best to add it to the shell app and share it in the external apps
