### ISSUE TITLE
Error to add new cli application to sample: "Uncaught (in promise): TypeError: Cannot read property 'AppModule' of undefined"

### ISSUE THREAD

**Issue by marcelo-vrgs** [MrFrankel/share-loader#8]
Hi guys!

I tried to create add a new external module to the project with the following steps:
- ng new menu 
-- Would you like to add Angular routing? Y
-- Which stylesheet format would you like to use? CSS
- npm i share-loader --save-dev
- npm i @angular-builders/custom-webpack --save-dev
- create file extra-webpack.config.js
`const path = require('path');
const {Externals} = require('share-loader');
module.exports = {
  entry: {
    'main': './src/app/app.external.module.ts'
  },
  externals: [
    Externals({
      namespace: 'container-app',
      modules: [/@angular/]
    })
  ],
  output: {
    filename: '[name].js',
    path: path.resolve('./dist'),
    chunkFilename: '[name].js',
    library: 'menu',
    libraryTarget: 'umd'
  },
  optimization: {
    runtimeChunk: false,
  }
}`
- add a build-ext section to angular.json
`        "build-ext": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./extra-webpack.config.js",
              "mergeStrategies": { "output": "replace", "entry": "replace", "externals": "replace" }
            },
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "none",
              "sourceMap": false,
              "extractCss": false ,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": false,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        }`
- create module app.common.module.ts
` import {NgModule} from '@angular/core';
import {AppComponent} from './app.component';
import { MainMenuComponent } from './main-menu/main-menu.component';

export const appModuleRoot: NgModule = {
  imports: [],
  declarations: [AppComponent, MainMenuComponent],
  bootstrap: [],
  providers: [],
  exports: []
};`
- app.module.ts:
`import {NgModule} from '@angular/core'
import {RouterModule} from '@angular/router'
import {appModuleRoot} from './app.common.module'
import {BrowserModule} from '@angular/platform-browser'
import {AppComponent} from './app.component'
import {appStates} from './app.states'

const appModule = appModuleRoot;
appModule.imports.push(BrowserModule, RouterModule.forRoot(appStates));
appModule.bootstrap.push(AppComponent);

@NgModule(appModule)

export class AppModule {
}`
-app.external.module.ts
`import {CommonModule} from '@angular/common'
import {NgModule} from '@angular/core'
import {RouterModule} from '@angular/router'
import {appModuleRoot} from './app.common.module'
import {appStates} from './app.states'

const appModule = appModuleRoot;
appModule.imports.push(CommonModule, RouterModule.forChild(appStates));

appModule.exports.push(RouterModule);
@NgModule(appModule)

export class AppModule {
}`
- app.states.ts
`import { MainMenuComponent } from './main-menu/main-menu.component';

export const appStates = [
  {
    path: '',
    component: MainMenuComponent
  }
]`
-run: `npm run ng run menu:build-ext`
- deploy dist folder to localhost/menu
- On shell-app/app.states.ts:
`export const appMenuState = {
  path: 'menu',

  /** Replace <%path-to-server-host%> with a server the will host the external application js**/
  loadChildren: () => {
    return loadScript('http://localhost/menu/main.js', 'menu', 'AppModule');
  }
};`

And I'm getting this error:
`core.js:15723 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'AppModule' of undefined
TypeError: Cannot read property 'AppModule' of undefined
    at sLoader.ts:35
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:17298)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17289)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17289)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)`

What am I doing wrong?

**Comment by marcelo-vrgs** [comment]
Hi!
I solve the problem just changing `importHelpers` to false on tsconfig.json

**Comment by MrFrankel** [comment]
@marcelo-vrgs gr8!, happy to hear, can we close this then?
