### ISSUE TITLE
How to deal with Multiple Router-Outlets (Auxiliary Routes)?

### ISSUE THREAD

**Issue by marcelo-vrgs** [MrFrankel/share-loader#9]
Hi!

I have a case where I need to load 3 router-outlets from main application. There is any way to do that?

- app.component.html
```
<router-outlet name="header"></router-outlet><!-- external componentes loaded here -->
<router-outlet name="sidebar"></router-outlet><!-- external componentes loaded here -->
<router-outlet></router-outlet><!-- external componentes loaded here -->
```

**Comment by MrFrankel** [comment]
This should work as useual, just add  `outlet: 'header'` to the route definition

**Comment by marcelo-vrgs** [comment]
Yes, you're right!

- component.html
```
      <router-outlet name="header"></router-outlet>
      <a [routerLink]="[{ outlets: {  header: ['header'] } }]">Header on header outlet</a> <br>
```

- app.states.ts
`export const appHeaderState = {
  path: 'header',
  outlet: 'header',
  loadChildren: () => {
    return loadScript('http://localhost/header/main.js', 'header6', 'AppModule');
  }
};
`
